ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS gstin VARCHAR(15),
  ADD COLUMN IF NOT EXISTS gstin_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS gstin_trade_name VARCHAR(200),
  ADD COLUMN IF NOT EXISTS gst_registration_type VARCHAR(50);

ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS gstin VARCHAR(15),
  ADD COLUMN IF NOT EXISTS gstin_verified BOOLEAN DEFAULT FALSE;
