ALTER TABLE proforma_invoices
  ADD COLUMN IF NOT EXISTS invoice_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS forex_rate NUMERIC(12,4) NOT NULL DEFAULT 83.5000,
  ADD COLUMN IF NOT EXISTS forex_rate_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS total_amount_fcy NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS total_amount_inr NUMERIC(15,2);

ALTER TABLE export_invoices
  ADD COLUMN IF NOT EXISTS invoice_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS forex_rate NUMERIC(12,4) NOT NULL DEFAULT 83.5000,
  ADD COLUMN IF NOT EXISTS forex_rate_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS forex_rate_source VARCHAR(50) DEFAULT 'Manual',
  ADD COLUMN IF NOT EXISTS total_amount_fcy NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS total_amount_inr NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS customs_assessable_value NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS duty_drawback_amount NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS realization_status VARCHAR(50) DEFAULT 'Pending';
