/**
 * TILE EXPORTER ERP SAAS
 * 
 * COPYRIGHT © 2026. ALL RIGHTS RESERVED.
 * 
 * PROPRIETARY AND CONFIDENTIAL:
 * This source code is the strictly confidential intellectual property of the 
 * Tile Exporter system. Unauthorized copying, modification, distribution, 
 * or reverse engineering of this file, via any medium, is strictly prohibited.
 */

/**
 * Enhanced Helper Functions
 * Comprehensive utility functions for the business management system
 */

/**
 * Generate placeholder invoice number (PI/MM/YY/001 format)
 * Actual number auto-generated by backend on save
 */
export const generateInvoiceNumber = () => {
  return `[AUTO]`;
};

/**
 * Generate unique order number with proper formatting
 */
export const generateOrderNumber = () => {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const year = String(now.getFullYear()).slice(-2);
  const ts = String(Date.now()).slice(-4);
  return `PO/${month}/${year}/${ts}`;
};

/**
 * Generate unique packing list number
 */

export const generatePackingListNumber = () => {
  // Implement logic or leave empty if not needed
  return '';
};

/**
 * Validate PAN (Permanent Account Number - Indian)
 */
export const validatePAN = (pan) => {
  if (!pan) return false;
  const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
  return panRegex.test(pan.toUpperCase());
};

/**
 * Format phone number
 */
export const formatPhoneNumber = (phone) => {
  if (!phone) return '';
  const cleaned = phone.replace(/\D/g, '');
  if (cleaned.length === 10) return `+91 ${cleaned.slice(0, 5)} ${cleaned.slice(5)}`;
  if (cleaned.length === 12) return `+${cleaned.slice(0, 2)} ${cleaned.slice(2, 7)} ${cleaned.slice(7)}`;
  return phone;
};

/**
 * Check if email is valid
 */
export const isValidEmail = (email) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

/**
 * Check if phone is valid (Indian format)
 */
export const isValidPhone = (phone) => {
  const phoneRegex = /^(\+91|0)?[6-9]\d{9}$/;
  return phoneRegex.test(phone.replace(/\s/g, ''));
};

/**
 * Convert camelCase to snake_case
 */
export const camelToSnake = (str) => {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
};

/**
 * Convert snake_case to camelCase
 */
export const snakeToCamel = (str) => {
  return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
};

/**
 * Transform entire object keys from snake_case to camelCase
 */
export const transformSnakeToCamelKeys = (obj) => {
  if (Array.isArray(obj)) {
    return obj.map((item) => transformSnakeToCamelKeys(item));
  } else if (obj !== null && typeof obj === 'object') {
    return Object.keys(obj).reduce((newObj, key) => {
      const camelKey = snakeToCamel(key);
      newObj[camelKey] = transformSnakeToCamelKeys(obj[key]);
      return newObj;
    }, {});
  }
  return obj;
};

/**
 * Transform entire object keys from camelCase to snake_case
 */
export const transformCamelToSnakeKeys = (obj) => {
  if (Array.isArray(obj)) {
    return obj.map((item) => transformCamelToSnakeKeys(item));
  } else if (obj !== null && typeof obj === 'object') {
    return Object.keys(obj).reduce((newObj, key) => {
      const snakeKey = camelToSnake(key);
      newObj[snakeKey] = transformCamelToSnakeKeys(obj[key]);
      return newObj;
    }, {});
  }
  return obj;
};

/**
 * Get initials from name
 */
export const getInitials = (name) => {
  if (!name) return '';
  return name
    .split(' ')
    .map((word) => word[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
};

/**
 * Truncate text with ellipsis
 */
export const truncateText = (text, length = 50) => {
  if (!text) return '';
  return text.length > length ? `${text.slice(0, length)}...` : text;
};

/**
 * Format large numbers with commas
 */
export const formatNumber = (number) => {
  if (!number && number !== 0) return '';
  return parseFloat(number).toLocaleString('en-IN');
};

/**
 * Calculate age from date of birth
 */
export const calculateAge = (dob) => {
  if (!dob) return 0;
  const today = new Date();
  const birthDate = new Date(dob);
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDiff = today.getMonth() - birthDate.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  return age;
};

/**
 * Get days between two dates
 */
export const getDaysBetween = (date1, date2) => {
  const oneDay = 24 * 60 * 60 * 1000;
  const firstDate = new Date(date1);
  const secondDate = new Date(date2);
  return Math.round(Math.abs((firstDate - secondDate) / oneDay));
};

/**
 * Format date to ISO format (YYYY-MM-DD)
 */
export const formatDateISO = (date) => {
  if (!date) return '';
  const d = new Date(date);
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${d.getFullYear()}-${month}-${day}`;
};

/**
 * Add days to a date
 */
export const addDays = (date, days) => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
};

/**
 * Check if date is valid
 */
export const isValidDate = (date) => {
  return date instanceof Date && !isNaN(date);
};

/**
 * Deep clone object
 */
export const deepClone = (obj) => {
  if (obj === null || typeof obj !== 'object') return obj;
  if (obj instanceof Date) return new Date(obj.getTime());
  if (obj instanceof Array) return obj.map((item) => deepClone(item));
  if (obj instanceof Object) {
    const clonedObj = {};
    for (const key in obj) {
      if (obj.hasOwnProperty(key)) {
        clonedObj[key] = deepClone(obj[key]);
      }
    }
    return clonedObj;
  }
};

/**
 * Merge two objects (shallow merge)
 */
export const mergeObjects = (obj1, obj2) => {
  return { ...obj1, ...obj2 };
};

/**
 * Check if object is empty
 */
export const isEmptyObject = (obj) => {
  return Object.keys(obj).length === 0;
};

/**
 * Get unique values from array
 */
export const getUniqueValues = (array, key = null) => {
  if (key) {
    return [...new Map(array.map((item) => [item[key], item])).values()];
  }
  return [...new Set(array)];
};

/**
 * Group array by key
 */
export const groupByKey = (array, key) => {
  return array.reduce((result, item) => {
    const group = item[key];
    if (!result[group]) {
      result[group] = [];
    }
    result[group].push(item);
    return result;
  }, {});
};

/**
 * Sort array of objects by key
 */
export const sortByKey = (array, key, order = 'asc') => {
  return [...array].sort((a, b) => {
    if (a[key] < b[key]) return order === 'asc' ? -1 : 1;
    if (a[key] > b[key]) return order === 'asc' ? 1 : -1;
    return 0;
  });
};

/**
 * Filter array by multiple conditions
 */
export const filterByConditions = (array, conditions) => {
  return array.filter((item) => {
    return Object.keys(conditions).every((key) => {
      if (typeof conditions[key] === 'function') {
        return conditions[key](item[key]);
      }
      return item[key] === conditions[key];
    });
  });
};

/**
 * Get value from nested object
 */
export const getNestedValue = (obj, path) => {
  return path.split('.').reduce((value, key) => value?.[key], obj);
};

/**
 * Set value in nested object
 */
export const setNestedValue = (obj, path, value) => {
  const keys = path.split('.');
  let current = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!(key in current) || typeof current[key] !== 'object') {
      current[key] = {};
    }
    current = current[key];
  }
  current[keys[keys.length - 1]] = value;
  return obj;
};

/**
 * Debounce function
 */
export const debounce = (func, wait) => {
  let timeout;
  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
};

/**
 * Throttle function
 */
export const throttle = (func, wait) => {
  let timeout;
  return function executedFunction(...args) {
    const later = () => {
      timeout = null;
      func(...args);
    };
    if (!timeout) {
      func(...args);
      timeout = setTimeout(later, wait);
    }
  };
};

/**
 * Sleep/delay function (for async operations)
 */
export const sleep = (ms) => {
  return new Promise((resolve) => setTimeout(resolve, ms));
};

/**
 * Generate random string
 */
export const generateRandomString = (length = 8) => {
  return Math.random().toString(36).substring(2, length + 2);
};

/**
 * Generate random color
 */
export const generateRandomColor = () => {
  return `#${Math.floor(Math.random() * 16777215).toString(16)}`;
};

/**
 * Check if string contains only numbers
 */
export const isNumeric = (str) => {
  return /^\d+$/.test(str);
};

/**
 * Capitalize first letter
 */
export const capitalizeFirstLetter = (str) => {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
};

/**
 * Capitalize all words
 */
export const capitalizeWords = (str) => {
  if (!str) return '';
  return str
    .split(' ')
    .map((word) => capitalizeFirstLetter(word))
    .join(' ');
};

/**
 * Convert bytes to human readable format
 */
export const formatBytes = (bytes, decimals = 2) => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
};

/**
 * Escape HTML special characters
 */
export const escapeHtml = (text) => {
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
};

/**
 * Generate UUID v4
 */
export const generateUUID = () => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

/**
 * Format time (HH:MM:SS)
 */
export const formatTime = (seconds) => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
};

/**
 * Parse query string
 */
export const parseQueryString = (queryString) => {
  const params = new URLSearchParams(queryString);
  const result = {};
  params.forEach((value, key) => {
    result[key] = value;
  });
  return result;
};

/**
 * Build query string from object
 */
export const buildQueryString = (params) => {
  return new URLSearchParams(params).toString();
};

/**
 * Workflow Connections System
 * Tracks relationships between documents (invoices, orders, packing lists, etc.)
 */
export const workflowConnections = {
  /**
   * Get related documents for a given document number
   */
  getRelatedDocuments: (documentNo) => {
    return {
      orders: [],
      packingLists: [],
      shipments: [],
      invoices: [],
    };
  },

  /**
   * Get workflow status for a document
   */
  getWorkflowStatus: (documentNo) => {
    return {
      current: 'draft',
      progress: 0,
      steps: ['Draft', 'Approved', 'Processing', 'Completed'],
    };
  },

  /**
   * Update linked document status
   */
  updateLinkedStatus: async (documentNo, newStatus) => {
    return { success: true, message: 'Status updated' };
  },

  /**
   * Get workflow connections map
   */
  getConnectionMap: () => {
    return {};
  },
};

/**
 * Rate History Manager
 * Manages historical pricing/rate data for products and orders
 */
export const rateHistoryManager = {
  /**
   * Get rate history for a product
   */
  getRateHistory: (productId) => {
    return [];
  },

  /**
   * Add rate to history
   */
  addRateToHistory: (productId, rate, date = new Date()) => {
    return { success: true, message: 'Rate added to history' };
  },

  /**
   * Get best rate for a product in period
   */
  getBestRate: (productId, startDate, endDate) => {
    return null;
  },

  /**
   * Get average rate for a product
   */
  getAverageRate: (productId) => {
    return 0;
  },

  /**
   * Save client rate for pricing history
   */
  saveClientRate: (clientName, productName, rate, currency = 'INR') => {
    return { 
      success: true, 
      message: `Rate saved for ${clientName}/${productName}`,
      clientName,
      productName,
      rate,
      currency,
      savedAt: new Date().toISOString()
    };
  },

  /**
   * Get client rate for a product
   */
  getClientRate: (clientName, productName) => {
    return null; // Returns null if no rate history found
  },

  /**
   * Save supplier rate for pricing history
   */
  saveSupplierRate: (supplierName, productName, rate, currency = 'INR') => {
    return { 
      success: true, 
      message: `Rate saved for ${supplierName}/${productName}`,
      supplierName,
      productName,
      rate,
      currency,
      savedAt: new Date().toISOString()
    };
  },

  /**
   * Get supplier rate for a product
   */
  getSupplierRate: async (supplierName, productName) => {
    return 0; // Returns 0 if no rate history found
  },
};

/**
 * Global Search Function
 * Searches across all modules and returns matching results
 */
export const globalSearch = (query, modules = []) => {
  return {
    results: [],
    count: 0,
    query,
  };
};




